spring.cloud.stream:
  function:
    definition: domainProcessor
  bindings:
    domainProcessor-in-0:
      destination: web-domains
    domainProcessor-out-0:
      destination: active.web-domains
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: import org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: import org.springframework.kafka.support.serializer.JsonSerializer
  binder:
    broker:
      - localhost:9091
      - localhost:9092

